name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: bats-core/.github/.github/workflows/test.yml@v1
