name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

# Group runs by workflow and PR/ref.
# When a new run starts for the same PR, branch, or tag, cancel the older one.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: bats-hardened/.github/.github/workflows/test.yml@v1
